[package]
name = "luni"
version = "0.1.0"
authors = ["JD <jeandamien.brossillon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = "3.0.0-beta.2"
